// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderKind } from "./ProviderKind";

/**
 * How to reach one model backend.
 */
export type ProviderConfig = { 
/**
 * Stable id used in the UI and in session records.
 */
id: string, kind: ProviderKind, base_url: string, 
/**
 * Default model to select when this provider is chosen.
 */
default_model: string | null, 
/**
 * Name of the environment variable holding the API key.
 *
 * The key itself is never written here: a config file full of secrets is
 * the thing users accidentally commit.
 */
api_key_env: string | null, 
/**
 * Overrides for backends that cannot be probed. Ignored for Ollama, which
 * reports its own capabilities per model.
 */
native_tools: boolean | null, context_length: number | null, 
/**
 * Path prefix the OpenAI-compatible routes live under. Defaults to `/v1`,
 * which is right for OpenAI, vLLM, LM Studio, llama.cpp, and OpenVINO
 * Model Server from 2026.3 on; earlier OVMS builds need `/v3`.
 */
api_prefix: string | null, };
