// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of the two config layers a value is read from or written to.
 *
 * Ordering matters: [`Scope::Workspace`] is applied after [`Scope::Global`]
 * and wins on conflict.
 */
export type Scope = "global" | "workspace";
