// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a listing shows, read from a transcript's own opening lines.
 */
export type SessionMeta = { id: string, workspace: string, model: string, 
/**
 * Unix seconds. Formatting is the frontend's business.
 *
 * Declared to TypeScript as `number` rather than the `bigint` a `u64`
 * would otherwise become: seconds since 1970 stay exact in a double until
 * the year 285-million-odd, and `bigint` would cost every consumer a
 * conversion for precision no timestamp will ever use.
 */
started: number, 
/**
 * Unix seconds, from the file's own mtime — the last turn recorded.
 */
updated: number, 
/**
 * The first thing asked, shortened. Empty for a session with no turns.
 */
title: string, };
