// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Preferences that survive a restart.
 */
export type Settings = { last_workspace: string | null, last_provider: string | null, last_model: string | null, 
/**
 * Whether the agent may propose skills on its own after a turn.
 */
skill_synthesis_enabled: boolean, };
