// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StopReason } from "./StopReason";
import type { TokenUsage } from "./TokenUsage";

export type UiEvent = { "type": "iteration_started", iteration: number, } | { "type": "text_delta", text: string, } | { "type": "thinking_delta", text: string, } | { "type": "tool_call_started", id: string, name: string, 
/**
 * Human-readable summary of the specific call.
 */
preview: string, } | { "type": "tool_call_finished", id: string, ok: boolean, 
/**
 * Tool output, truncated for display.
 */
output: string, } | { "type": "compacted", messages_removed: number, } | { "type": "turn_finished", stop_reason: StopReason, usage: TokenUsage, } | { "type": "error", message: string, };
