// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Scope } from "./Scope";

/**
 * One persisted rule and the layer it came from.
 */
export type AllowedRule = { rule: string, scope: Scope, };
