// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a tool does to the world. Drives the permission tier.
 */
export type Effect = "read" | "write" | "execute" | "network";
