// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effect } from "./Effect";

export type PermissionRequest = { id: string, tool: string, effect: Effect, 
/**
 * One line describing this specific call.
 */
preview: string, 
/**
 * What "always allow" would grant, in words, so the user knows the scope
 * of the broader decision they are being offered.
 */
always_scope: string, input: unknown, };
