// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which layer a persisted decision belongs to.
 *
 * The same two layers the config files use. It is defined here because this
 * is the lowest crate that needs the distinction; `taurus-host` re-exports it
 * so there is one `Scope` and one TypeScript type across the whole harness.
 */
export type Scope = "global" | "workspace";
