// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderConfig } from "./ProviderConfig";
import type { ServerStatus } from "./ServerStatus";
import type { Settings } from "./Settings";

export type AppStatus = { workspace: string, providers: Array<ProviderConfig>, settings: Settings, skill_count: number, skill_problems: Array<string>, tool_names: Array<string>, mcp_servers: Array<ServerStatus>, };
