// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContentBlock = { "type": "text", text: string, } | { "type": "thinking", text: string, } | { "type": "tool_use", id: string, name: string, input: unknown, } | { "type": "tool_result", tool_use_id: string, content: string, is_error: boolean, } | { "type": "image", mime_type: string, 
/**
 * Base64, no data-URI prefix.
 */
data: string, };
