// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatedSession = { id: string, model: string, provider_id: string, 
/**
 * False when the model has no native tool support and the prompted
 * fallback will be used. Shown in the UI because it changes reliability.
 */
native_tools: boolean, context_length: number, };
