// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaveTarget } from "./SaveTarget";
import type { SkillProposal } from "./SkillProposal";

export type ProposalResponse = { id: string, approve: boolean, 
/**
 * Where to save it. Ignored when rejecting.
 */
target: SaveTarget | null, 
/**
 * The user's edits, if they changed anything in the review card.
 */
edited: SkillProposal | null, };
