// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Message } from "./Message";

/**
 * What a resumed conversation needs to be redrawn and continued.
 */
export type ResumedSession = { id: string, model: string, provider_id: string, native_tools: boolean, context_length: number, 
/**
 * The whole transcript, for the frontend to rebuild the view from.
 */
messages: Array<Message>, };
