// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a specific model on a specific backend can do.
 *
 * Resolved per model, not per provider: on Ollama, `qwen3.6:27b` supports
 * native tool calls and `gemma3` does not, from the same server.
 */
export type Capabilities = { 
/**
 * False means the harness must fall back to prompted tool calling.
 */
native_tools: boolean, vision: boolean, 
/**
 * Model emits separable reasoning content.
 */
thinking: boolean, context_length: number, };
