// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelInfo = { id: string, display_name: string, 
/**
 * None when the backend does not report it; callers fall back to
 * `Capabilities::context_length`.
 */
context_length: number | null, };
