// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenUsage } from "./TokenUsage";

/**
 * The single stream shape every provider adapter must produce.
 *
 * Providers that deliver tool calls atomically rather than incrementally
 * (Ollama does this) emit `ToolUseStart`, one `ToolUseInputDelta` carrying the
 * whole JSON, then `ToolUseEnd`. Consumers cannot tell the difference.
 */
export type StreamEvent = { "type": "text_delta", text: string, } | { "type": "thinking_delta", text: string, } | { "type": "tool_use_start", id: string, name: string, } | { "type": "tool_use_input_delta", id: string, json: string, } | { "type": "tool_use_end", id: string, } | { "type": "usage", usage: TokenUsage, };
