// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an approved proposal gets written.
 */
export type SaveTarget = "project" | "user";
