// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillScript } from "./SkillScript";
import type { SkillTier } from "./SkillTier";

/**
 * A skill summary for the UI. Excludes the body, which can be long.
 */
export type SkillSummary = { name: string, description: string, when_to_use: string, version: number, tier: SkillTier, scripts: Array<SkillScript>, degraded: string | null, dir: string, };
