// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProposedScript } from "./ProposedScript";

export type SkillProposal = { id: string, name: string, description: string, when_to_use: string, 
/**
 * The procedure, as markdown.
 */
body: string, scripts: Array<ProposedScript>, 
/**
 * Why the agent thinks this is worth keeping. Shown in the review card;
 * never written to disk.
 */
rationale: string, 
/**
 * True when a skill of this name already exists and would be replaced.
 */
replaces_existing: boolean, };
