// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a skill came from. Later tiers shadow earlier ones by name, so a
 * project can override a personal skill that does not fit it.
 */
export type SkillTier = "builtin" | "user" | "project";
