// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SkillScript = { 
/**
 * Path relative to the skill directory.
 */
path: string, 
/**
 * Logical interpreter name: `python3`, `node`, `bash`, `sh`, `pwsh`.
 */
interpreter: string, 
/**
 * What the script does and what arguments it takes.
 */
description: string, };
